import React, { createContext, useState, useEffect } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { supabase } from '../lib/supabase';
import { useAuth } from './AuthContext';

export const StoreContext = createContext();

export default function StoreContextProvider({ children }) {
  const { user } = useAuth();
  const [isStoreLoading, setIsStoreLoading] = useState(true);

  // Initialize state as empty (Cloud-First)
  const [customers, setCustomers] = useState([]);
  const [inventory, setInventory] = useState([
    // Keep these as "Seed" data for empty states or remove if preferred
    // I will leave them empty as per "Fully Cloud" requirement
  ]);
  const [invoices, setInvoices] = useState([]);
  const [quotes, setQuotes] = useState([]);
  const [leads, setLeads] = useState([]);
  const [activityLogs, setActivityLogs] = useState([]);
  const [expenses, setExpenses] = useState([]);
  const [payments, setPayments] = useState([]);

  // SMS Configuration (Base Defaults)
  const [smsConfig, setSmsConfig] = useState({
    apiKey: '2179165276941c4e5eb994053957585',
    email: 'seynextech@gmail.com',
    senderID: 'QKSendDemo',
    companyName: 'Seynex Technology',
    dashboardName: 'GymSales Pro',
    receiptLogo: '',
    companyAddress: 'No 680/1B, Hendrik Perera Road, Gonwala, Kelaniya',
    companyPhone: '072 840 8880',
    adminPhone: '072 840 8880',
    companyEmail: 'seynextech@gmail.com',
    bankDetails: {
      accountName: 'B M A P K DE SILVA',
      bank: 'Sampath Bank',
      branch: 'Ratmalana Branch',
      accountNumber: '1018 5281 9432'
    },
    quoteTemplate: 'Hi {name},\nHere is your quotation for {gym}.\nTotal Amount: LKR {amount}\nView your Quote here: {link}',
    thankYouTemplate: 'Hi {name},\nThank you! We have received payment for Invoice {invoiceNumber}.\nYour account is up to date.',
    renewalTemplate: 'Hi {name},\nNotice: Your annual software renewal of LKR {amount} for {gym} is due on {date}. Please contact us to renew.',
    invoiceReminderTemplate: 'Hi {name},\nReminder: Payment of LKR {amount} for Invoice {invoiceNumber} is due on {date}. Please arrange payment.',
    birthdayTemplate: 'Happy Birthday {name}! Wishing you and the team at {gym} a fantastic year ahead! - {companyName}',
    cashReceivedTemplate: 'Hi {name},\nCash Received! We have successfully received a deposit of LKR {amount} for {documentType} #{number}. Thank you!',
    autoRenewalEnabled: false,
    autoRenewalDays: '15,7,1',
    autoInvoiceEnabled: false,
    autoInvoiceDays: 3,
    birthdayWishEnabled: true,
    smsHeader: '',
    smsFooter: '',
    smsEncoding: 'GSM',
    deliveryReports: true,
    pdfColor: '#3b82f6',
    pdfFooterText: 'Thank you for your business. Please process payment promptly.',
    pdfNotes: 'This document is generated by GymSales Pro Management System.',
    sessionTimeout: 5,
    balance: 0,
    invoicePrefix: 'INV-',
    nextInvoiceNumber: 1001,
    quotePrefix: 'QT-',
    nextQuoteNumber: 1001,
    debtorNudgeTemplate: 'Hi {name},\nThis is a friendly reminder that you have an outstanding balance of LKR {remainingBalance} for Invoice {invoiceNumber}. Please settle as soon as possible. Thank you!'
  });

  const [theme, setTheme] = useState(() => {
    const saved = localStorage.getItem('gym_theme');
    if (saved) return saved;
    return window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark';
  });

  const toggleTheme = () => setTheme(prev => prev === 'dark' ? 'light' : 'dark');

  const [notification, setNotification] = useState(null);
  
  // Realtime System Notifications (for Bell)
  const [systemNotifications, setSystemNotifications] = useState([]);
  
  const markNotificationsRead = () => setSystemNotifications([]);

  const showNotification = (message, type = 'success') => {
    setNotification({ message, type });
    setTimeout(() => setNotification(null), 3000);
  };

  // Save theme to localStorage (UI Preference only)
  useEffect(() => { 
    localStorage.setItem('gym_theme', theme);
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  const resetToSeynexDefaults = async () => {
    if (window.confirm("This will permanently remove your cloud account data. Proceed?")) {
      if (!user) return;
      try {
          await Promise.all([
            supabase.from('customers').delete().eq('user_id', user.id),
            supabase.from('inventory').delete().eq('user_id', user.id),
            supabase.from('quotations').delete().eq('user_id', user.id),
            supabase.from('invoices').delete().eq('user_id', user.id),
            supabase.from('leads').delete().eq('user_id', user.id),
            supabase.from('expenses').delete().eq('user_id', user.id),
            supabase.from('payments').delete().eq('user_id', user.id),
            supabase.from('activity_logs').delete().eq('user_id', user.id),
            supabase.from('user_profiles').delete().eq('user_id', user.id)
          ]);
          localStorage.clear();
          window.location.reload();
      } catch (err) {
          console.error('Reset error:', err);
      }
    }
  };

  const generateShareKey = () => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 4; i++) {
      code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return `SNX-${code}`;
  };

  // --- SUPABASE SYNC LOGIC ---
  const syncQuoteToSupabase = async (quote) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('quotations')
        .upsert({
          id: quote.id,
          user_id: user.id,
          share_key: quote.shareKey,
          quote_number: quote.quoteNumber,
          date: quote.date,
          prospect_name: quote.prospectName,
          prospect_phone: quote.prospectPhone,
          amount: quote.amount,
          status: quote.status,
          items: quote.items
        });
      if (error) console.error('[Supabase Sync] Quote Error:', error);
    } catch (err) {
      console.error('[Supabase Sync] Quote Exception:', err);
    }
  };

  const syncInvoiceToSupabase = async (invoice) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('invoices')
        .upsert({
          id: invoice.id,
          user_id: user.id,
          share_key: invoice.shareKey,
          invoice_number: invoice.invoiceNumber,
          date: invoice.date,
          due_date: invoice.dueDate,
          customer_id: (invoice.customerId && invoice.customerId !== 'unknown') ? invoice.customerId : null,
          prospect_name: invoice.prospectName || customers.find(c => c.id === invoice.customerId)?.gymName || '',
          amount: invoice.amount,
          status: invoice.status,
          items: invoice.items,
          reminder_sent: invoice.reminderSent || false
        });
      if (error) console.error('[Supabase Sync] Invoice Error:', error);
    } catch (err) {
      console.error('[Supabase Sync] Invoice Exception:', err);
    }
  };

  const syncCustomerToSupabase = async (customer) => {
    if (!user) {
      console.error('[Supabase Sync] No user session - cannot save customer');
      return;
    }
    try {
      const { error } = await supabase
        .from('customers')
        .upsert({
          id: customer.id,
          user_id: user.id,
          gym_name: customer.gymName,
          name: customer.name,
          email: customer.email,
          phone: customer.phone,
          dob: customer.dob,
          purchase_date: customer.purchaseDate,
          renewal_date: customer.renewalDate,
          annual_fee: customer.annualFee,
          status: customer.status,
          notes: customer.notes || []
        });
      if (error) {
        console.error('[Supabase Sync] Customer Error:', error);
        showNotification(`Cloud save failed: ${error.message}`, 'error');
      } else {
        console.log('[Supabase Sync] Customer saved OK:', customer.gymName);
      }
    } catch (err) {
      console.error('[Supabase Sync] Customer Exception:', err);
      showNotification(`Cloud save error: ${err.message}`, 'error');
    }
  };

  const syncInventoryToSupabase = async (item) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('inventory')
        .upsert({
          id: item.id,
          user_id: user.id,
          name: item.name,
          item_type: item.type,
          price: item.price,
          cost_price: item.costPrice || 0,
          reorder_level: item.reorderLevel || 5,
          stock: item.stock,
          description: item.desc
        });
      if (error) {
        console.error('[Supabase Sync] Inventory Error:', error);
        showNotification(`Inventory sync failed: ${error.message}`, 'error');
      }
    } catch (err) {
      console.error('[Supabase Sync] Inventory Exception:', err);
      showNotification(`Inventory exception: ${err.message}`, 'error');
    }
  };

  const syncLeadToSupabase = async (lead) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('leads')
        .upsert({
          id: lead.id,
          user_id: user.id,
          address: lead.address,
          gym_name: lead.gymName,
          prospect_name: lead.prospectName,
          phone: lead.phone,
          status: lead.status,
          date: lead.date,
          notes: lead.notes
        });
      if (error) {
        console.error('[Supabase Sync] Lead Error:', error);
        showNotification(`Lead sync failed: ${error.message}`, 'error');
      }
    } catch (err) {
      console.error('[Supabase Sync] Lead Exception:', err);
      showNotification(`Lead exception: ${err.message}`, 'error');
    }
  };

  const syncExpenseToSupabase = async (expense) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('expenses')
        .upsert({
          id: expense.id,
          user_id: user.id,
          category: expense.category,
          amount: expense.amount,
          date: expense.date,
          description: expense.description
        });
      if (error) {
        console.error('[Supabase Sync] Expense Error:', error);
        showNotification(`Expense sync failed: ${error.message}`, 'error');
      }
    } catch (err) {
      console.error('[Supabase Sync] Expense Exception:', err);
      showNotification(`Expense exception: ${err.message}`, 'error');
    }
  };

  const syncPaymentToSupabase = async (payment) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('payments')
        .upsert({
          id: payment.id,
          user_id: user.id,
          customer_id: payment.customerId,
          document_id: payment.documentId,
          amount: payment.amount,
          payment_type: payment.type,
          payment_timestamp: payment.timestamp
        });
      if (error) console.error('[Supabase Sync] Payment Error:', error);
    } catch (err) {
      console.error('[Supabase Sync] Payment Exception:', err);
    }
  };

  const syncLogToSupabase = async (log) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('activity_logs')
        .upsert({
          id: log.id,
          user_id: user.id,
          log_type: log.type,
          message: log.message,
          details: log.details,
          log_timestamp: log.timestamp
        });
      if (error) console.error('[Supabase Sync] Log Error:', error);
    } catch (err) {
      console.error('[Supabase Sync] Log Exception:', err);
    }
  };

  const syncConfigToSupabase = async (config) => {
    if (!user) return;
    try {
      const { error } = await supabase
        .from('user_profiles')
        .upsert({
          user_id: user.id,
          config,
          updated_at: new Date().toISOString()
        });
      if (error) console.error('[Supabase Sync] Config Error:', error);
    } catch (err) {
      console.error('[Supabase Sync] Config Exception:', err);
    }
  };

  const fetchCloudData = async () => {
    if (!user) {
      setIsStoreLoading(false);
      return;
    }
    
    try {
      console.log('[Supabase Sync] Fetching all business data...');
      setIsStoreLoading(true);

      const safeFetch = async (table, query) => {
        try {
          const { data, error } = await query;
          if (error) {
            console.error(`[Supabase Sync] Error fetching ${table}:`, error);
            return null;
          }
          return data;
        } catch (e) {
          console.error(`[Supabase Sync] Exception fetching ${table}:`, e);
          return null;
        }
      };
      
      const fetchResults = await Promise.all([
        safeFetch('customers', supabase.from('customers').select('*').eq('user_id', user.id)),
        safeFetch('inventory', supabase.from('inventory').select('*').eq('user_id', user.id)),
        safeFetch('quotations', supabase.from('quotations').select('*').eq('user_id', user.id)),
        safeFetch('invoices', supabase.from('invoices').select('*').eq('user_id', user.id)),
        safeFetch('leads', supabase.from('leads').select('*').eq('user_id', user.id)),
        safeFetch('expenses', supabase.from('expenses').select('*').eq('user_id', user.id)),
        safeFetch('payments', supabase.from('payments').select('*').eq('user_id', user.id)),
        safeFetch('activity_logs', supabase.from('activity_logs').select('*').eq('user_id', user.id).order('log_timestamp', { ascending: false }).limit(500)),
        safeFetch('user_profiles', supabase.from('user_profiles').select('config').eq('user_id', user.id).single())
      ]);

      const [cData, invData, qData, iData, lData, eData, pData, logData, profData] = fetchResults;

      console.log('[Supabase Sync] Fetch results - Customers:', cData?.length ?? 'ERROR', '| Invoices:', iData?.length ?? 'ERROR');

      if (cData === null) showNotification('Could not load clients from cloud. Check console for details.', 'error');

      if (profData?.config) {
        setSmsConfig(prev => {
          const merged = { ...prev, ...profData.config };
          // IMPORTANT: Mirror cloud config to local storage for the PDF generator
          localStorage.setItem('gym_sms_config', JSON.stringify(merged));
          return merged;
        });
      }

      if (cData) setCustomers(cData.map(c => ({
        id: c.id, gymName: c.gym_name, name: c.name, email: c.email, phone: c.phone,
        dob: c.dob, purchaseDate: c.purchase_date, renewalDate: c.renewal_date, 
        annualFee: Number(c.annual_fee), status: c.status, notes: c.notes || []
      })));

      if (invData) setInventory(invData.map(i => ({
        id: i.id, name: i.name, type: i.item_type, 
        price: Number(i.price) || 0, 
        costPrice: Number(i.cost_price ?? Math.round((Number(i.price) || 0) * 0.7)),
        reorderLevel: Number(i.reorder_level ?? 5),
        stock: Number(i.stock) || 0, 
        desc: i.description
      })));

      if (qData) setQuotes(qData.map(q => ({
        id: q.id, shareKey: q.share_key, quoteNumber: q.quote_number, date: q.date,
        prospectName: q.prospect_name, prospectPhone: q.prospect_phone, amount: Number(q.amount),
        status: q.status, items: q.items || []
      })));

      if (iData) {
        const todayDate = new Date();
        todayDate.setHours(0, 0, 0, 0);

        const loadedInvoices = iData.map(inv => {
          let parsed = {
            id: inv.id, shareKey: inv.share_key, invoiceNumber: inv.invoice_number, date: inv.date,
            dueDate: inv.due_date, customerId: inv.customer_id || 'unknown', amount: Number(inv.amount),
            status: inv.status, items: inv.items || [], prospectName: inv.prospect_name, reminderSent: inv.reminder_sent
          };

          // TIER 1 FEATURE: Overdue Invoice Auto-Flag
          if (parsed.status !== 'Paid' && parsed.status !== 'Overdue' && parsed.dueDate) {
            const due = new Date(parsed.dueDate);
            due.setHours(0, 0, 0, 0);
            if (due < todayDate) {
              parsed.status = 'Overdue';
              // Sync updated status to Supabase asynchronously
              supabase.from('invoices').update({ status: 'Overdue' }).eq('id', parsed.id).then(({ error }) => {
                if (error) console.error('[Auto-Flag] Invoice Sync Error:', error);
                else {
                  console.log(`[Auto-Flag] Marked ${parsed.invoiceNumber} as Overdue.`);
                }
              });
            }
          }
          return parsed;
        });

        setInvoices(loadedInvoices);
      }

      if (lData) setLeads(lData.map(l => ({
        id: l.id, gymName: l.gym_name, prospectName: l.prospect_name, phone: l.phone,
        status: l.status, date: l.date, notes: l.notes
      })));

      if (eData) setExpenses(eData.map(e => ({
        id: e.id, category: e.category, amount: Number(e.amount), date: e.date, description: e.description
      })));

      if (pData) setPayments(pData.map(p => ({
        id: p.id, customerId: p.customer_id, documentId: p.document_id, amount: Number(p.amount),
        type: p.payment_type, timestamp: p.payment_timestamp
      })));

      if (logData) setActivityLogs(logData.map(l => ({
        id: l.id, type: l.log_type, message: l.message, details: l.details, timestamp: l.log_timestamp
      })));

      console.log('[Supabase Sync] Load complete.');
    } catch (err) {
      console.error('[Supabase Sync] Global Fetch Exception:', err);
    } finally {
      setIsStoreLoading(false);
    }
  };

  // REALTIME SUBSCRIPTION FOR QUOTES
  useEffect(() => {
    if (!user) return;
    
    const channel = supabase
      .channel('schema-db-changes')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'quotations', filter: `user_id=eq.${user.id}` },
        (payload) => {
          console.log('[Realtime] Quotation Changed:', payload);
          if (payload.eventType === 'UPDATE') {
            const oldItem = quotes.find(q => q.id === payload.new.id);
            if (oldItem && oldItem.status !== payload.new.status) {
              if (payload.new.status === 'Accepted') {
                showNotification(`🎉 Quotation for ${payload.new.prospect_name} was ACCEPTED!`, 'success');
                // Push to bell notifications
                setSystemNotifications(prev => [{
                  id: crypto.randomUUID(),
                  message: `Quote #${payload.new.quote_number} accepted by ${payload.new.prospect_name}`,
                  time: new Date().toISOString(),
                  type: 'success'
                }, ...prev]);
              } else if (payload.new.status === 'Rejected') {
                showNotification(`Quotation #${payload.new.quote_number} was Declined.`, 'info');
                setSystemNotifications(prev => [{
                  id: crypto.randomUUID(),
                  message: `Quote #${payload.new.quote_number} declined by ${payload.new.prospect_name}`,
                  time: new Date().toISOString(),
                  type: 'error'
                }, ...prev]);
              }
              // Refresh local state to reflect change
              fetchCloudData();
            }
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [user, quotes]);

  // Fetch from cloud on login
  useEffect(() => {
    if (user) fetchCloudData();
  }, [user]);

  // Actions
  const toggleTheme = () => setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  const addCustomer = (customer) => {
    const newCustomer = { 
      ...customer, 
      id: uuidv4(),
      notes: [] 
    };
    setCustomers([...customers, newCustomer]);
    syncCustomerToSupabase(newCustomer);
    addLog('System', `Added new Active Gym: ${customer.gymName}`);
  };

  const deleteCustomer = async (id) => {
    setCustomers(customers.filter(c => c.id !== id));
    if (user) {
      await supabase.from('customers').delete().eq('id', id);
    }
  };

  const updateCustomer = (id, updatedData) => {
    setCustomers(prev => prev.map(c => {
      if (c.id === id) {
        const updated = { ...c, ...updatedData };
        syncCustomerToSupabase(updated);
        return updated;
      }
      return c;
    }));
  };
  
  const addCustomerNote = (customerId, text) => {
    if (!text.trim()) return;
    setCustomers(prev => prev.map(c => {
      if (c.id === customerId) {
        const newNote = {
          id: uuidv4(),
          date: new Date().toISOString(),
          text
        };
        const updatedNotes = [newNote, ...(c.notes || [])];
        const updated = { ...c, notes: updatedNotes };
        syncCustomerToSupabase(updated);
        addLog('Status', `Update logged for ${c.gymName}: ${text.substring(0, 30)}...`);
        return updated;
      }
      return c;
    }));
  };
  
  const addLog = (type, message, details = '') => {
    const newLog = {
      id: uuidv4(),
      timestamp: new Date().toISOString(),
      type, 
      message,
      details
    };
    setActivityLogs(prev => [newLog, ...prev].slice(0, 500));
    syncLogToSupabase(newLog);
  };

  const addInventoryItem = (item) => {
    const newItem = { ...item, id: uuidv4() };
    setInventory([...inventory, newItem]);
    syncInventoryToSupabase(newItem);
  };

  const deleteInventoryItem = async (id) => {
    setInventory(inventory.filter(i => i.id !== id));
    if (user) {
      await supabase.from('inventory').delete().eq('id', id);
    }
  };

  const updateInventoryItem = (id, data) => {
    setInventory(prev => prev.map(i => {
      if (i.id === id) {
        const updated = { ...i, ...data };
        syncInventoryToSupabase(updated);
        return updated;
      }
      return i;
    }));
  };
  
  const addInvoice = (invoice) => {
    const newInvoice = { ...invoice, id: uuidv4(), shareKey: generateShareKey(), status: 'Draft' };
    setInvoices([...invoices, newInvoice]);
    syncInvoiceToSupabase(newInvoice);

    // Auto-increment Next Invoice Number if it matches the current sequence
    const currentPrefix = smsConfig.invoicePrefix || 'INV-';
    const currentNext = parseInt(smsConfig.nextInvoiceNumber || 1001);
    if (invoice.invoiceNumber === `${currentPrefix}${currentNext}`) {
        updateSmsConfig({ ...smsConfig, nextInvoiceNumber: currentNext + 1 });
    }
  };

  const deleteInvoice = async (id) => {
    setInvoices(invoices.filter(i => i.id !== id));
    if (user) {
      await supabase.from('invoices').delete().eq('id', id);
    }
  };

  const updateInvoice = (id, data) => {
    const updatedInvoices = invoices.map(i => {
      if (i.id === id) {
        const updated = { ...i, ...data };
        syncInvoiceToSupabase(updated);
        return updated;
      }
      return i;
    });
    setInvoices(updatedInvoices);
  };
  
  const updateInvoiceStatus = (id, status) => {
    setInvoices(invoices.map(i => {
      if (i.id === id) {
        const updated = { ...i, status };
        addLog('Status', `Invoice ${i.invoiceNumber} status changed to ${status}`);
        syncInvoiceToSupabase(updated);
        if (status === 'Paid' && i.status !== 'Paid') {
          const customer = customers.find(c => c.id === i.customerId);
          if(customer && customer.phone) {
            triggerSMS('Payment', customer, i);
          }
        }
        return updated;
      }
      return i;
    }));
  };

  const addQuote = (quote) => {
    const newQuote = { ...quote, id: uuidv4(), shareKey: generateShareKey(), status: 'Pending' };
    setQuotes([...quotes, newQuote]);
    syncQuoteToSupabase(newQuote);

    // Auto-increment Next Quote Number if it matches current sequence
    const currentPrefix = smsConfig.quotePrefix || 'QT-';
    const currentNext = parseInt(smsConfig.nextQuoteNumber || 1001);
    if (quote.quoteNumber === `${currentPrefix}${currentNext}`) {
        updateSmsConfig({ ...smsConfig, nextQuoteNumber: currentNext + 1 });
    }
  };

  const deleteQuote = async (id) => {
    setQuotes(quotes.filter(q => q.id !== id));
    if (user) {
      await supabase.from('quotations').delete().eq('id', id);
    }
  };

  const updateQuote = (id, updatedData) => {
    setQuotes(quotes.map(q => {
      if (q.id === id) {
        const updated = { ...q, ...updatedData };
        syncQuoteToSupabase(updated);
        return updated;
      }
      return q;
    }));
  };

  const updateQuoteStatus = async (id, status) => {
    setQuotes(prev => prev.map(q => q.id === id ? { ...q, status } : q));
    
    // Cloud Sync
    const { error } = await supabase.from('quotations').update({ status }).eq('id', id);
    if (error) {
      console.error('[Supabase Sync] Quote Status Error:', error);
      showNotification('Could not update status in cloud.', 'error');
      return;
    }

    // MANAGER NOTIFICATION ON ACCEPTANCE
    if (status === 'Accepted') {
      const quote = quotes.find(q => q.id === id);
      if (quote) {
        addLog('System', `Quote #${quote.quoteNumber} accepted by customer.`);
        
        // Final Alert Logic: Target Admin/Owner Phone specifically
        const alertPhone = smsConfig.adminPhone || smsConfig.companyPhone;
        if (alertPhone) {
          const alertMsg = `🚀 BUSINESS WIN: Quotation #${quote.quoteNumber} has been ACCEPTED by ${quote.prospectName}. Value: LKR ${quote.amount.toLocaleString()}. Please process next steps.`;
          sendDirectSMS(alertPhone, alertMsg);
        }
      }
    }
  };

  const convertQuoteToInvoice = (quoteId) => {
    const quote = quotes.find(q => q.id === quoteId);
    if (!quote) return;

    let customer = customers.find(c => c.gymName === quote.prospectName || c.phone === quote.prospectPhone);
    if (!customer) {
        customer = customers.find(c => c.gymName === quote.prospectName);
    }

    const newInvoice = {
      id: uuidv4(),
      shareKey: generateShareKey(),
      invoiceNumber: `INV-${quote.quoteNumber.split('-')[1] || Math.floor(Math.random() * 10000)}`,
      date: new Date().toISOString().split('T')[0],
      dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], 
      customerId: customer ? customer.id : 'unknown',
      prospectName: !customer ? quote.prospectName : undefined, 
      items: quote.items,
      amount: quote.amount,
      status: 'Draft'
    };

    setInvoices(prev => [...prev, newInvoice]);
    syncInvoiceToSupabase(newInvoice);
    updateQuoteStatus(quoteId, 'Accepted');
    addLog('System', `Converted Quote ${quote.quoteNumber} to Invoice ${newInvoice.invoiceNumber}`);
    showNotification(`Converted! New invoice ${newInvoice.invoiceNumber} created.`);
    return newInvoice;
  };

  const recordCashDeposit = (data) => {
    const { customerId, documentId, amount, paymentType } = data; 
    
    const newPayment = {
      id: uuidv4(),
      timestamp: new Date().toISOString(),
      customerId,
      documentId,
      amount,
      type: 'Cash'
    };

    setPayments(prev => [...prev, newPayment]);
    syncPaymentToSupabase(newPayment);

    if (paymentType === 'Invoice') {
      const invoice = invoices.find(inv => inv.id === documentId);
      if (invoice) {
        const historicalPayments = payments
          .filter(p => p.documentId === documentId)
          .reduce((sum, p) => sum + p.amount, 0);
        const totalPaid = historicalPayments + amount;

        if (totalPaid >= invoice.amount) {
           updateInvoiceStatus(documentId, 'Paid');
        } else if (totalPaid > 0 && totalPaid < invoice.amount) {
           updateInvoiceStatus(documentId, 'Partially Paid');
        }
      }
    }

    const customer = customers.find(c => c.id === customerId);
    if (customer && customer.phone) {
        triggerSMS('CashReceived', customer, { ...data, amount, documentType: paymentType, number: documentId });
    }

    addLog('Status', `Cash deposit of LKR ${amount.toLocaleString()} received for ${paymentType}`);
    showNotification(`Deposit of LKR ${amount.toLocaleString()} recorded!`);
  };

  const addLead = (lead) => {
    const newLead = { ...lead, id: uuidv4(), date: new Date().toISOString() };
    setLeads([...leads, newLead]);
    syncLeadToSupabase(newLead);
    addLog('System', `New Lead Added: ${lead.gymName}`);
  };
  const updateLead = (id, data) => {
    setLeads(prev => prev.map(l => {
        if (l.id === id) {
            const updated = { ...l, ...data };
            syncLeadToSupabase(updated);
            return updated;
        }
        return l;
    }));
  };
  const deleteLead = async (id) => {
    setLeads(leads.filter(l => l.id !== id));
    if (user) {
        await supabase.from('leads').delete().eq('id', id);
    }
  };

  const addExpense = (exp) => {
    const newExpense = { ...exp, id: uuidv4(), date: new Date().toISOString() };
    setExpenses([...expenses, newExpense]);
    syncExpenseToSupabase(newExpense);
  };
  const deleteExpense = async (id) => {
    setExpenses(expenses.filter(e => e.id !== id));
    if (user) {
        await supabase.from('expenses').delete().eq('id', id);
    }
  };

  // Automated Scheduler for Renewals and Invoices
  useEffect(() => {
    let updatedCustomers = [...customers];
    let customersChanged = false;
    
    let updatedInvoices = [...invoices];
    let invoicesChanged = false;
    
    const now = new Date();
    const today = new Date();
    today.setHours(0, 0, 0, 0); 
    
    // Only trigger automated schedules from 8:00 AM onwards
    if (now.getHours() < 8) return;
    
    // 1. Check Renewals
    if (smsConfig?.autoRenewalEnabled) {
      const daysArray = String(smsConfig.autoRenewalDays || '7').split(',').map(d => parseInt(d.trim(), 10)).filter(d => !isNaN(d));

      customers.forEach((c, index) => {
        if (c.renewalDate && c.status === 'Active') {
          const renewalDate = new Date(c.renewalDate);
          renewalDate.setHours(0, 0, 0, 0);
          const timeDiff = renewalDate.getTime() - today.getTime();
          const daysDiff = Math.ceil(timeDiff / (1000 * 3600 * 24));
          
          if (daysArray.includes(daysDiff)) {
            // Prevent multiple sends on the same exact day
            if (c.lastReminderDaysDiff !== daysDiff) {
              console.log(`[Auto Schedule] Sending renewal SMS to ${c.name} (${c.gymName})`);
              // Trigger actual SMS
              triggerSMS('Renewal', c, null);
              showNotification(`Auto-scheduled renewal reminder sent to ${c.gymName}`);
              updatedCustomers[index] = { ...c, lastReminderDaysDiff: daysDiff };
              customersChanged = true;
            }
          }
        }
      });
    }

    // 2. Check Pending/Draft/Sent Invoices
    if (smsConfig?.autoInvoiceEnabled) {
      invoices.forEach((inv, index) => {
        if (!inv.reminderSent && inv.status !== 'Paid' && inv.dueDate) {
          const dueDate = new Date(inv.dueDate);
          dueDate.setHours(0, 0, 0, 0);
          const timeDiff = dueDate.getTime() - today.getTime();
          const daysDiff = Math.ceil(timeDiff / (1000 * 3600 * 24));
          
          if (daysDiff <= (smsConfig.autoInvoiceDays || 3) && daysDiff >= 0) {
            const customer = customers.find(c => c.id === inv.customerId);
            if (customer) {
              // Trigger actual SMS
              triggerSMS('InvoiceReminder', customer, inv);
              showNotification(`Auto-scheduled invoice reminder sent to ${customer.gymName}`);
              updatedInvoices[index] = { ...inv, reminderSent: true };
              invoicesChanged = true;
            }
          }
        }
      });
    }

    // 3. Check Birthdays
    if (smsConfig?.birthdayWishEnabled) {
      customers.forEach((c, index) => {
        if (c.dob && c.status === 'Active') {
          const dob = new Date(c.dob);
          const currentYear = today.getFullYear();
          
          if (dob.getMonth() === today.getMonth() && dob.getDate() === today.getDate()) {
            // Check if already sent this year
            if (c.lastBirthdaySentYear !== currentYear) {
              // Trigger actual SMS
              triggerSMS('Birthday', c, null);
              showNotification(`Auto-scheduled birthday wish sent to ${c.name}`);
              updatedCustomers[index] = { ...c, lastBirthdaySentYear: currentYear };
              customersChanged = true;
            }
          }
        }
      });
    }

    if (customersChanged) setCustomers(updatedCustomers);
    if (invoicesChanged) setInvoices(updatedInvoices);
  }, []); // Run once on startup

  // SMS Service Core
  const updateSmsConfig = (newConfig) => {
    setSmsConfig(newConfig);
    syncConfigToSupabase(newConfig);
  };

  const getBasicAuthHeader = () => {
    return 'Basic ' + btoa(`${smsConfig.email}:${smsConfig.apiKey}`);
  };

  const fetchSmsBalance = async () => {
    try {
      const response = await fetch('/api/quicksend?FUN=CHECK_BALANCE', {
        method: 'POST',
        headers: {
          'Authorization': getBasicAuthHeader(),
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({})
      });

      // Quicksend returns plain text (a number) for CHECK_BALANCE, not JSON
      const rawText = await response.text();

      // Try to parse as JSON first, fallback to plain text
      let balanceVal;
      try {
        const parsed = JSON.parse(rawText);
        balanceVal = parsed.balance ?? parsed.Balance ?? parsed.credit ?? rawText;
      } catch {
        balanceVal = rawText.trim();
      }

      // Update the stored balance in state — this will reflect live in the UI
      setSmsConfig(prev => ({ ...prev, balance: balanceVal }));

    } catch (e) {
      console.error('Balance fetch error:', e);
      setSmsConfig(prev => ({ ...prev, balance: 'Error' }));
    }
  };

  const sendDirectSMS = async (phone, rawMessage) => {
    try {
      const payload = {
        senderID: smsConfig.senderID || "SEYNEX",
        to: phone,
        msg: rawMessage
      };

      const res = await fetch('/api/quicksend?FUN=SEND_SINGLE', {
        method: 'POST',
        headers: {
          'Authorization': getBasicAuthHeader(),
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      console.log('SMS Send Result:', data);
      showNotification(`Sent successfully to ${phone}!`);
      addLog('SMS', `Sent to ${phone}: ${rawMessage.substring(0, 50)}...`);
    } catch (err) {
      console.error('Failed to send SMS API', err);
      showNotification('Error connecting to QuickSend API.', 'error');
    }
  };

  const sendBulkSMSArray = async (phonesArray, rawMessage) => {
    try {
      const payload = {
        check_cost: false,
        senderID: smsConfig.senderID || "SEYNEX",
        to: phonesArray,
        msg: rawMessage
      };

      const res = await fetch('/api/quicksend?FUN=SEND_BULK_SAME', {
        method: 'POST',
        headers: {
          'Authorization': getBasicAuthHeader(),
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      console.log('Bulk SMS Send Result:', data);
      showNotification(`Broadcast sent to ${phonesArray.length} contacts!`);
      addLog('SMS', `Bulk Broadcast to ${phonesArray.length} recipients.`);
    } catch (err) {
      console.error('Failed to send Bulk API', err);
      showNotification('Error connecting to QuickSend API for Broadcast.', 'error');
    }
  };

  const handleTestSms = (templateStr) => {
    let msg = templateStr;
    
    // Apply Global Formatting
    if (smsConfig.smsHeader) msg = `${smsConfig.smsHeader}\n${msg}`;
    if (smsConfig.smsFooter) msg = `${msg}\n${smsConfig.smsFooter}`;

    msg = msg
      .replace(/{name}/g, 'John Doe')
      .replace(/{gym}/g, 'FitLife Gym')
      .replace(/{companyName}/g, smsConfig.companyName || 'Seynex Technology')
      .replace(/{amount}/g, '15,000')
      .replace(/{date}/g, new Date().toLocaleDateString())
      .replace(/{days_left}/g, '7')
      .replace(/{invoiceNumber}/g, 'INV-9999')
      .replace(/{renewalDate}/g, new Date().toLocaleDateString())
      .replace(/{dueDate}/g, new Date().toLocaleDateString())
      .replace(/{phone}/g, '0712345678')
      .replace(/{bankName}/g, smsConfig.bankDetails?.bank || 'Sample Bank')
      .replace(/{accountNumber}/g, smsConfig.bankDetails?.accountNumber || '0000 0000 0000')
      .replace(/{accountName}/g, smsConfig.bankDetails?.accountName || 'Sample Name')
      .replace(/{link}/g, 'https://example.com/pay');
    
    alert(`[TEST SMS PREVIEW]\n\n${msg}\n\nLength: ${msg.length} characters`);
  };

  const triggerSMS = (type, customer, documentData) => {
    let msg = '';
    
    // Default fallback values
    const cName = customer?.name || documentData?.prospectName || 'Customer';
    const cGym = customer?.gymName || documentData?.prospectName || 'Gym';
    
    let template = '';
    
    if (type === 'Quotation') template = smsConfig.quoteTemplate || '';
    else if (type === 'Payment') template = smsConfig.thankYouTemplate || '';
    else if (type === 'Renewal') template = smsConfig.renewalTemplate || '';
    else if (type === 'InvoiceReminder') template = smsConfig.invoiceReminderTemplate || '';
    else if (type === 'Birthday') template = smsConfig.birthdayTemplate || '';
    else if (type === 'CashReceived') template = smsConfig.cashReceivedTemplate || '';
    else if (type === 'DebtorNudge') template = smsConfig.debtorNudgeTemplate || '';

    let templateWithBranding = template;
    if (smsConfig.smsHeader) templateWithBranding = `${smsConfig.smsHeader}\n${templateWithBranding}`;
    if (smsConfig.smsFooter) templateWithBranding = `${templateWithBranding}\n${smsConfig.smsFooter}`;

    msg = templateWithBranding
      .replace(/{name}/g, cName)
      .replace(/{gym}/g, cGym)
      .replace(/{companyName}/g, smsConfig.companyName || 'Seynex Technology')
      .replace(/{amount}/g, (documentData?.amount || customer?.annualFee || 0).toLocaleString())
      .replace(/{remainingBalance}/g, (documentData?.remainingBalance || 0).toLocaleString())
      .replace(/{date}/g, documentData?.dueDate ? new Date(documentData.dueDate).toLocaleDateString() : customer?.renewalDate ? new Date(customer.renewalDate).toLocaleDateString() : '')
      .replace(/{invoiceNumber}/g, documentData?.invoiceNumber || '')
      .replace(/{number}/g, documentData?.invoiceNumber || documentData?.quoteNumber || '')
      .replace(/{documentType}/g, documentData?.documentType || 'Document')
      .replace(/{link}/g, (documentData?.id || documentData?.shareKey) ? `${window.location.origin}/share/${
        type.toLowerCase() === 'quotation' ? 'quote' : 
        type.toLowerCase() === 'cashreceived' ? 'receipt' : 'invoice'
      }/${documentData.id || documentData.shareKey}` : '')
      .replace(/{renewalDate}/g, customer?.renewalDate ? new Date(customer.renewalDate).toLocaleDateString() : '')
      .replace(/{dueDate}/g, documentData?.dueDate ? new Date(documentData.dueDate).toLocaleDateString() : '')
      .replace(/{phone}/g, customer?.phone || documentData?.prospectPhone || '')
      .replace(/{bankName}/g, smsConfig.bankDetails?.bank || '')
      .replace(/{accountNumber}/g, smsConfig.bankDetails?.accountNumber || '')
      .replace(/{accountName}/g, smsConfig.bankDetails?.accountName || '');

    if(customer?.phone || documentData?.prospectPhone) {
      sendDirectSMS(customer?.phone || documentData?.prospectPhone, msg);
    } else {
      showNotification(`Could not send SMS: No phone number saved`, 'error');
    }
  };

  return (
    <StoreContext.Provider value={{
      customers, addCustomer, deleteCustomer, updateCustomer,
      inventory, addInventoryItem, deleteInventoryItem, updateInventoryItem,
      invoices, addInvoice, updateInvoice, updateInvoiceStatus,
      quotes, addQuote, updateQuoteStatus, updateQuote, convertQuoteToInvoice,
      leads, addLead, updateLead, deleteLead,
      expenses, addExpense, deleteExpense,
      payments, recordCashDeposit,
      activityLogs, addLog,
      addCustomerNote,
      deleteInvoice, deleteQuote,
      smsConfig, updateSmsConfig, fetchSmsBalance, triggerSMS, sendDirectSMS, sendBulkSMSArray, handleTestSms,
      theme, toggleTheme,
      notification, showNotification,
      systemNotifications, markNotificationsRead,
      resetToSeynexDefaults,
      isStoreLoading
    }}>
      {children}
    </StoreContext.Provider>
  );
}
